version: "3"
services:
  hamachi:
    build: hamachi
    container_name: hamachi
    restart: unless-stopped
    volumes:
      - config:/var/lib/logmein-hamachi:rw
      - /etc/localtime:/etc/localtime
    privileged: true
    network_mode: "host"
    environment:
      - ACCOUNT=<ACCOUNT EMAIL>
